### ISSUE TITLE
Import Data option doesn't appear in Settings activity 

### ISSUE THREAD

**Issue by takieddine01** [christoffer/readtracker#20]
the solution is the same of the issue #19

**Comment by takieddine01** [comment]
I fix the problem in my local copy by downgrading the version number of the libraries : appcompact and support like this :
from
          **compile 'com.android.support:appcompat-v7:23.2.0
             compile 'com.android.support:support-v4:23.2.0**
to 
         **compile 'com.android.support:appcompat-v7:23.1.1
           compile 'com.android.support:support-v4:23.1.1**

in the gradle file

**Comment by christoffer** [comment]
See #19 (Closed because it seems to go away when upgrading the SDK to version 24)
