### ISSUE TITLE
Primitive and Object Types in DB layer classes

### ISSUE THREAD

**Issue by peter-tackage** [christoffer/readtracker#3]
I've just noticed that the model classes use a mixture of primitive and object types 

Classes using primitive types:
https://github.com/christoffer/readtracker/blob/master/app/src/main/java/com/readtracker/android/db/Session.java

Classes using object types:
https://github.com/christoffer/readtracker/blob/master/app/src/main/java/com/readtracker/android/db/Book.java
https://github.com/christoffer/readtracker/blob/master/app/src/main/java/com/readtracker/android/db/Quote.java

Also the id field in the parent Model object is a primitive.

Now, I don't know how much difference it makes; perhaps performance/memory usage would be better using primitives, it depends what ORMLite is doing under the covers. 

If only for the reason of consistency they should be the same (I'd lean towards primitives unless you have a reason otherwise or it would require a DB migration to update)

**Comment by christoffer** [comment]
This was a really long time ago, but I think the primitive vs native types were for optional vs. required fields?

Not really sure why all the fields are optional though :)

But closing this out since I don't think it's worth the migration headache for the payoff :P
